created: 2023-05-08T19:35:04.152Z
creator:
  id: 653f338b-c6b2-40ae-8ce3-042cc0f66243
  name: Levon Arakeylan
deletedAt: null
deployedCommitId: 5e23bb60-b33d-418b-93d6-e1f84cd80cc0
folderId: "null"
id: cc59e8fd-5db6-49e0-8197-94848237b431
isDeployed: true
isEditable: true
isPublic: false
name: Levon's Great App
organizationId: 441f8c45-985a-4f7e-bd1e-ec028536e222
pages:
  - id: 48163481-6a23-482b-bdca-0a321b211262
    isDefault: true
settings:
  profiles:
    deployed:
      availableProfileIds:
        - b1b7daf2-c9fc-42ee-b508-a71301617b99
        - bb88dc34-eb54-41c6-b3e1-f49faaea5d0f
      defaultProfileId: bb88dc34-eb54-41c6-b3e1-f49faaea5d0f
    editor:
      availableProfileIds:
        - b1b7daf2-c9fc-42ee-b508-a71301617b99
        - bb88dc34-eb54-41c6-b3e1-f49faaea5d0f
      defaultProfileId: b1b7daf2-c9fc-42ee-b508-a71301617b99
    preview:
      availableProfileIds:
        - b1b7daf2-c9fc-42ee-b508-a71301617b99
        - bb88dc34-eb54-41c6-b3e1-f49faaea5d0f
      defaultProfileId: bb88dc34-eb54-41c6-b3e1-f49faaea5d0f
updated: 2023-06-12T16:03:35.366Z
userPermissions:
  - manage:applications
  - read:applications
  - publish:applications
  - makePublic:applications
